development:
  base_url: http://localhost:8888/sugarce # where your SugarCRM instance is located
  username: bug_portal
  password: asdf

test:
  base_url: http://localhost:8888/sugarce # where your SugarCRM instance is located
  username: bug_portal
  password: asdf

production:
  base_url: http://localhost:8888/sugarce # where your SugarCRM instance is located
  username: bug_portal
  password: asdf

